version: '2'

services:
    api:
      image: comicrelief/php7-slim:latest
      ports:
       - "9001:80"
      volumes:
      - ./app/api:/var/www/html/
      links:
      - db-mysql
      environment:
        APPLICATION_ENV: local

    db-mysql:
        image: mysql:5.7
        ports:
          - "3306:3306"
        volumes:
          - ./app/data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo-manager
            
    front-end:
        image: nginx:1.13.2
        ports:
          - "8080:80"
        volumes:
          - ./docker/nginx/conf:/etc/nginx/conf.d/default.conf
          - ./docker/nginx/logs/error.log:/var/log/nginx/error.log
          - ./docker/nginx/logs/access.log:/var/log/nginx/access.log
          - ./app/angular-cli/dist:/usr/share/nginx/html
        

